CREATE TABLE IF NOT EXISTS `Employees` (`id` INTEGER auto_increment , `name` VARCHAR(255) NOT NULL, `surname` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `phone` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `role` ENUM('administrator', 'operator', 'technician') NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
SHOW INDEX FROM `Employees`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Customers' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `Customers` (`id` INTEGER auto_increment , `name` VARCHAR(255) NOT NULL, `surname` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `phone` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `flag` TINYINT(1) NOT NULL DEFAULT false, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
SHOW INDEX FROM `Customers`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Tickets' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `Tickets` (`id` INTEGER auto_increment , `subject` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `category` ENUM('help', 'repair', 'maintenance') NOT NULL, `priority` ENUM('low', 'medium', 'high', 'critical') NOT NULL, `status` ENUM('open', 'in_progress', 'closed') NOT NULL, `customerId` INTEGER NOT NULL, `technicianId` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`customerId`) REFERENCES `Customers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`technicianId`) REFERENCES `Employees` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
SHOW INDEX FROM `Tickets`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Actions' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `Actions` (`id` INTEGER auto_increment , `employeeId` INTEGER NOT NULL, `ticketId` INTEGER NOT NULL, `category` ENUM('assignation', 'edit', 'call', 'repair', 'document') NOT NULL, `description` TEXT NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`employeeId`) REFERENCES `Employees` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`ticketId`) REFERENCES `Tickets` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
SHOW INDEX FROM `Actions`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Components' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `Components` (`id` INTEGER auto_increment , `name` VARCHAR(255) NOT NULL, `quantity` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
SHOW INDEX FROM `Components`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'ActionsComponents' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `ActionsComponents` (`id` INTEGER auto_increment , `actionId` INTEGER NOT NULL, `componentId` INTEGER NOT NULL, `quantity` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`actionId`) REFERENCES `Actions` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`componentId`) REFERENCES `Components` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
SHOW INDEX FROM `ActionsComponents`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'Comments' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `Comments` (`id` INTEGER auto_increment , `employeeId` INTEGER NOT NULL, `ticketId` INTEGER NOT NULL, `description` TEXT NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`employeeId`) REFERENCES `Employees` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`ticketId`) REFERENCES `Tickets` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
SHOW INDEX FROM `Comments`
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'RevokedTokens' AND TABLE_SCHEMA = 'easystance_db'
CREATE TABLE IF NOT EXISTS `RevokedTokens` (`id` INTEGER NOT NULL auto_increment , `token` VARCHAR(255) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
SHOW INDEX FROM `RevokedTokens`
